[package]
name = "compass-core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
duckdb = { workspace = true }
egui-charts = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-tracy = { workspace = true, optional = true }
tracy-client-sys = { workspace = true, optional = true }

[features]
tracy = ["dep:tracing-tracy", "dep:tracy-client-sys", "tracy-client-sys/enable"]

[dev-dependencies]
httpmock = { workspace = true }
tempfile = { workspace = true }
rstest = { workspace = true }
toml = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "parquet_bench"
harness = false

[[bench]]
name = "duckdb_bench"
harness = false
