[package]
name = "compass-collectors"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
csv = { workspace = true }
encoding_rs = { workspace = true }
ipnet = { workspace = true }
rand = { workspace = true }
redis = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
wreq = { workspace = true }
wreq-util = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
httpmock = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
