//! Shared data model types.
//!
//! Contains commands, application state, configuration, and stock metadata
//! used by both the GUI and CLI binaries.

use chrono::{DateTime, Utc};
use egui_charts::model::Bar;
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Symbol identifiers
// ---------------------------------------------------------------------------

/// Info returned by symbol search (code + display name).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SymbolInfo {
    /// Exchange-prefixed stock symbol (e.g. "SZ000001").
    pub code: String,
    /// Chinese display name (e.g. "平安银行").
    pub name: String,
}

/// Live market data for a stock.
///
/// Fetched from realtime API. All fields are optional — the API
/// may return `null` for any field, especially outside trading hours.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RealtimeQuote {
    /// Price-to-earnings ratio.
    pub pe: Option<f64>,
    /// Price-to-book ratio.
    pub pb: Option<f64>,
    /// Total share capital (万股).
    pub total_share: Option<f64>,
    /// Floating share capital (万股).
    pub float_share: Option<f64>,
    /// Daily price ceiling (涨停价).
    pub up_limit: Option<f64>,
    /// Daily price floor (跌停价).
    pub down_limit: Option<f64>,
}

/// Core stock metadata.
///
/// Contains the stock's identifying information: symbol, display name,
/// industry classification, market segment, and listing dates.
/// Stored in `stock_basic.parquet` (generated by `import-compass`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StockBasic {
    /// Stock symbol (exchange-prefixed, e.g. "SZ000001").
    pub symbol: String,
    /// Chinese display name.
    pub name: String,
    /// Geographic area.
    pub area: Option<String>,
    /// Industry classification.
    pub industry: Option<String>,
    /// Market segment (e.g. "主板", "创业板").
    pub market: Option<String>,
    /// Board segment (主板/创业板/科创板/北交所).
    pub board: Option<String>,
    /// Company full legal name.
    pub full_name: Option<String>,
    /// Total share capital (总股本).
    pub total_share: Option<f64>,
    /// First trading date.
    pub list_date: Option<chrono::NaiveDate>,
    /// Last trading date (if delisted).
    pub delist_date: Option<chrono::NaiveDate>,
}

/// A single cross-section row: one trading day of one symbol.
///
/// Returned by [`crate::data::parquet::ParquetReader::fetch_cross_section`]
/// for whole-market scans. Unlike a chart `Bar`, it carries the `symbol` and
/// `adjclose` fields that technical screening conditions require. Since the
/// SEPA extension (epic #139) it also carries raw `open`/`high`/`low`/`amount`
/// for shape (VCP), ATR and turnover (成交额) factors.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrossSectionBar {
    /// Stock symbol (exchange-prefixed, e.g. "SZ000001").
    pub symbol: String,
    /// Trading date.
    pub trade_date: chrono::NaiveDate,
    /// Raw (unadjusted) open price.
    pub open: f64,
    /// Raw (unadjusted) high price.
    pub high: f64,
    /// Raw (unadjusted) low price.
    pub low: f64,
    /// Forward-adjusted (前复权) close price.
    pub adjclose: f64,
    /// Raw (unadjusted) close price.
    pub close: f64,
    /// Trading volume (shares).
    pub volume: f64,
    /// Trading amount (成交额, yuan).
    pub amount: f64,
}

/// A single (concept, stock) membership row of an EastMoney concept board.
///
/// Read from `concept_member.parquet` by
/// [`crate::data::parquet::ParquetReader::fetch_concept_member`]. Versioned by
/// `update_date` — a snapshot of memberships, not a per-day time series
/// (epic #139 decision 20).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConceptMember {
    /// Concept board code (e.g. "BK1169").
    pub concept_code: String,
    /// Stock symbol (exchange-prefixed, e.g. "SH600519").
    pub symbol: String,
    /// Concept board display name.
    pub concept_name: Option<String>,
    /// Date this membership row was last updated.
    pub update_date: Option<chrono::NaiveDate>,
}

/// Daily main-capital (主力资金) net flow for one symbol.
///
/// Read from `capital_main_flow.parquet` by
/// [`crate::data::parquet::ParquetReader::fetch_capital_main_flow`]. Net
/// inflow amounts are in yuan; `*_rate` is a percentage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapitalMainFlow {
    /// Stock symbol (exchange-prefixed, e.g. "SH600519").
    pub symbol: String,
    /// Trading date.
    pub trade_date: chrono::NaiveDate,
    /// Main capital net inflow (主力净流入, yuan).
    pub main_net_inflow: f64,
    /// Main capital net inflow rate (主力净流入占比, percent).
    pub main_net_inflow_rate: f64,
    /// Super-large order net inflow (超大单净流入, yuan).
    pub super_large_net: f64,
    /// Large order net inflow (大单净流入, yuan).
    pub large_net: f64,
    /// Medium order net inflow (中单净流入, yuan).
    pub medium_net: f64,
    /// Small order net inflow (小单净流入, yuan); null when the source omits it.
    pub small_net: Option<f64>,
    /// Date this row was last updated.
    pub update_date: Option<chrono::NaiveDate>,
}

/// One 龙虎榜 (dragon-tiger list) seat record for a symbol and trading day.
///
/// Read from `dragon_list.parquet` by
/// [`crate::data::parquet::ParquetReader::fetch_dragon_list`]. Amounts are in
/// yuan; a row may aggregate multiple seats of the same `seat_type`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DragonListRow {
    /// Stock symbol (exchange-prefixed, e.g. "SH600519").
    pub symbol: String,
    /// Trading date.
    pub trade_date: chrono::NaiveDate,
    /// Seat type (营业部/机构专用 etc.).
    pub seat_type: String,
    /// Total buy amount (买入额, yuan).
    pub buy_amount: f64,
    /// Total sell amount (卖出额, yuan).
    pub sell_amount: f64,
    /// Net amount (净买入额, yuan); null when both amounts are missing.
    pub net_amount: Option<f64>,
    /// 1 = institutional seat (机构专用), 0/None otherwise.
    pub institution_flag: Option<i8>,
    /// Date this row was last updated.
    pub update_date: Option<chrono::NaiveDate>,
}

/// One 大宗交易 (block trade) record.
///
/// Read from `block_trade.parquet` by
/// [`crate::data::parquet::ParquetReader::fetch_block_trade`]. `amount` is in
/// yuan; `premium_rate` is the discount/premium vs. the closing price in
/// percent (negative = discount).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockTradeRow {
    /// Stock symbol (exchange-prefixed, e.g. "SH600519").
    pub symbol: String,
    /// Trading date.
    pub trade_date: chrono::NaiveDate,
    /// Block trade price (成交价, yuan).
    pub price: f64,
    /// Block trade volume (成交量, shares).
    pub volume: f64,
    /// Block trade amount (成交额, yuan).
    pub amount: f64,
    /// Buyer name (买方营业部).
    pub buyer: Option<String>,
    /// Seller name (卖方营业部).
    pub seller: Option<String>,
    /// Premium rate vs. close (折溢价率, percent).
    pub premium_rate: Option<f64>,
    /// Date this row was last updated.
    pub update_date: Option<chrono::NaiveDate>,
}

/// One 机构调研 (institution survey) record.
///
/// Read from `institution_survey.parquet` by
/// [`crate::data::parquet::ParquetReader::fetch_institution_survey`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InstitutionSurveyRow {
    /// Stock symbol (exchange-prefixed, e.g. "SH600519").
    pub symbol: String,
    /// Survey date (调研日期).
    pub survey_date: chrono::NaiveDate,
    /// Investigating institution name (调研机构, e.g. 长信基金).
    pub org_name: String,
    /// Survey method (接待方式, e.g. 电话会议).
    pub survey_type: Option<String>,
    /// Date this row was last updated.
    pub update_date: Option<chrono::NaiveDate>,
}

/// Adjustment factor record from Baostock (per-day multiplier for price adjustment).
///
/// `adj_factor` is the cumulative adjustment factor for a given date. To compute
/// forward-adjusted (前复权) or backward-adjusted (后复权) prices, multiply the
/// unadjusted price by `adj_factor` and divide by the latest factor.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct AdjFactor {
    /// Trade date in "YYYYMMDD" format (e.g. "20250722").
    pub trade_date: String,
    /// Cumulative adjustment factor. 1.0 = no adjustment.
    pub adj_factor: f64,
}

// ---------------------------------------------------------------------------
// App command (UI → worker thread)
// ---------------------------------------------------------------------------

/// Commands sent from the UI to the backend worker.
///
/// Kept for backward compatibility with compass-data CLI which
/// uses `Cmd` internally for retry logic and batch processing.
#[derive(Debug, Clone)]
pub enum Cmd {
    /// Fetch OHLCV bars for a symbol/timeframe/date-range.
    FetchBars {
        /// Exchange-prefixed stock symbol (e.g. "SZ000001").
        symbol: String,
        /// Timeframe string (e.g. "1d", "1w").
        timeframe: String,
        /// Earliest date to fetch.
        range_start: DateTime<Utc>,
        /// Latest date to fetch.
        range_end: DateTime<Utc>,
    },
}

// ---------------------------------------------------------------------------
// Application config (loaded from ~/.config/compass/config.toml)
// ---------------------------------------------------------------------------

/// Root application configuration loaded from `~/.config/compass/config.toml`.
///
/// All fields use `#[serde(default)]` — missing keys fall back to the
/// per-struct `Default` implementation. Partial configs work.
#[derive(Debug, Clone, Deserialize, Default)]
pub struct AppConfig {
    #[serde(default)]
    /// Application behavior (default symbol, timeframe).
    pub app: AppSection,
    #[serde(default)]
    /// Parquet directory for stock_basic.parquet and stock_daily/.
    pub parquet: ParquetConfig,
    #[serde(default)]
    /// Dolt data directories for investment_data and compass_data.
    pub dolt: DoltConfig,
    #[serde(default = "default_theme")]
    /// GUI color theme name (e.g. "compass_dark").
    pub theme: String,
}

/// Parquet data directory configuration.
#[derive(Debug, Clone, Deserialize)]
pub struct ParquetConfig {
    #[serde(default = "default_parquet_dir")]
    /// Directory containing `stock_basic.parquet` and `stock_daily/` subdirectory.
    pub dir: String,
}

impl Default for ParquetConfig {
    fn default() -> Self {
        Self {
            dir: default_parquet_dir(),
        }
    }
}

fn default_parquet_dir() -> String {
    "/data/compass-data/parquet_data".into()
}

/// Dolt data directories — used by the data pipeline CLI.
#[derive(Debug, Clone, Deserialize)]
pub struct DoltConfig {
    #[serde(default = "default_investment_data_dir")]
    /// Directory for the Dolt `investment_data` repository (primary OHLCV source).
    pub investment_data_dir: String,
    #[serde(default = "default_compass_data_dir")]
    /// Directory for the Dolt `compass_data` repository (fundamentals, custom data).
    pub compass_data_dir: String,
}

impl Default for DoltConfig {
    fn default() -> Self {
        Self {
            investment_data_dir: default_investment_data_dir(),
            compass_data_dir: default_compass_data_dir(),
        }
    }
}

fn default_investment_data_dir() -> String {
    "/data/compass-data/investment_data".into()
}

fn default_compass_data_dir() -> String {
    "/data/compass-data/compass_data".into()
}
/// Application-level settings: default stock and timeframe on startup.
#[derive(Debug, Clone, Deserialize)]
pub struct AppSection {
    #[serde(default = "default_symbol")]
    /// Stock code displayed on startup.
    pub default_symbol: String,
    #[serde(default = "default_timeframe")]
    /// Timeframe displayed on startup (e.g. "1d").
    pub default_timeframe: String,
}

impl Default for AppSection {
    fn default() -> Self {
        Self {
            default_symbol: default_symbol(),
            default_timeframe: default_timeframe(),
        }
    }
}

fn default_symbol() -> String {
    "SZ000001".into()
}
fn default_timeframe() -> String {
    "1d".into()
}
fn default_theme() -> String {
    "compass_dark".into()
}

// ---------------------------------------------------------------------------
// Watchlist config ([watchlist] section)
// ---------------------------------------------------------------------------

/// Watchlist (自选股) configuration persisted to the `[watchlist]` section
/// of `~/.config/compass/config.toml`.
///
/// The GUI writes this section whenever the sidebar watchlist changes
/// (add/remove) and restores it on startup — same pattern as the `[screener]`
/// section.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct WatchlistConfig {
    /// Exchange-prefixed symbols in display order (sorted ascending on save).
    #[serde(default)]
    pub symbols: Vec<String>,
}

// ---------------------------------------------------------------------------
// Shared application state (UI + worker both access via Arc<Mutex<>>)
// ---------------------------------------------------------------------------

/// Bars keyed by (symbol, timeframe).
pub type BarsMap = std::collections::HashMap<(String, String), Vec<Bar>>;

/// Shared mutable state between the UI (main) and worker (tokio) threads.
///
/// Protected by `Arc<Mutex<>>` — the UI reads on every frame, the worker
/// writes after each async operation.
///
/// Note: bar version tracking (`bars_version`) has been removed. The egui-mobius
/// reactive architecture uses `Dynamic<T>` for automatic change propagation
/// instead of manual version comparison.
pub struct CompassState {
    /// All loaded OHLCV bars, keyed by (symbol, timeframe).
    pub bars: BarsMap,
    /// Currently viewed symbol.
    pub current_symbol: String,
    /// Currently viewed timeframe.
    pub current_timeframe: String,
    /// True while a fetch is in-flight.
    pub loading: bool,
    /// Last error message, if any.
    pub error: Option<String>,
}

impl CompassState {
    /// Create a new state with the given defaults.
    ///
    /// Bars start empty; loaded on first fetch.
    pub fn new(default_symbol: &str, default_timeframe: &str) -> Self {
        Self {
            bars: BarsMap::new(),
            current_symbol: default_symbol.to_string(),
            current_timeframe: default_timeframe.to_string(),
            loading: false,
            error: None,
        }
    }

    /// Replace bars for a given key.
    pub fn set_bars(&mut self, symbol: &str, timeframe: &str, new_bars: Vec<Bar>) {
        let key = (symbol.to_string(), timeframe.to_string());
        self.bars.insert(key, new_bars);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    fn make_bar(open: f64, close: f64) -> Bar {
        Bar {
            time: Utc::now(),
            open,
            high: open + 1.0,
            low: close - 1.0,
            close,
            volume: 1000.0,
        }
    }

    #[test]
    fn appconfig_empty_toml_falls_back_to_default_symbol() {
        let config: AppConfig = toml::from_str("").unwrap();
        assert_eq!(config.app.default_symbol, "SZ000001");
        assert_eq!(config.app.default_timeframe, "1d");
    }

    #[test]
    fn appconfig_from_toml_overrides_fields() {
        let config: AppConfig = toml::from_str(
            r#"[app]
default_symbol = "600519"
default_timeframe = "1w"
"#,
        )
        .unwrap();
        assert_eq!(config.app.default_symbol, "600519");
        assert_eq!(config.app.default_timeframe, "1w");
    }

    #[test]
    fn appconfig_parses_parquet_dir_from_toml() {
        let config: AppConfig = toml::from_str(
            r#"[parquet]
dir = "/custom/parquet"
"#,
        )
        .unwrap();
        assert_eq!(config.parquet.dir, "/custom/parquet");
    }

    #[test]
    fn appconfig_theme_defaults_to_compass_dark() {
        let config: AppConfig = toml::from_str("").unwrap();
        assert_eq!(config.theme, "compass_dark");
    }

    #[test]
    fn appconfig_theme_parses_from_toml() {
        let config: AppConfig = toml::from_str("theme = \"custom_sky\"").unwrap();
        assert_eq!(config.theme, "custom_sky");
    }

    #[test]
    fn set_bars_stores_data() {
        let mut s = CompassState::new("000001", "1d");
        s.set_bars("000001", "1d", vec![make_bar(10.0, 12.0)]);
        assert_eq!(s.bars.len(), 1);
    }

    #[test]
    fn set_bars_overwrites_existing_key() {
        let mut s = CompassState::new("000001", "1d");
        s.set_bars("000001", "1d", vec![make_bar(10.0, 12.0)]);
        s.set_bars("000001", "1d", vec![make_bar(20.0, 22.0)]);
        assert_eq!(s.bars.len(), 1);
    }

    #[test]
    fn set_bars_stores_multiple_symbols() {
        let mut s = CompassState::new("000001", "1d");
        s.set_bars("000001", "1d", vec![make_bar(10.0, 12.0)]);
        s.set_bars("600519", "1d", vec![make_bar(20.0, 22.0)]);
        assert_eq!(s.bars.len(), 2);
    }

    #[test]
    fn parquet_config_default_dir() {
        let cfg = ParquetConfig::default();
        assert_eq!(cfg.dir, "/data/compass-data/parquet_data");
    }

    #[test]
    fn appconfig_parquet_section_parses_from_toml() {
        let config: AppConfig = toml::from_str(
            r#"[parquet]
dir = "/custom/parquet/path"
"#,
        )
        .unwrap();
        assert_eq!(config.parquet.dir, "/custom/parquet/path");
    }

    #[test]
    fn appconfig_parquet_section_falls_back_to_default() {
        let config: AppConfig = toml::from_str("").unwrap();
        assert_eq!(config.parquet.dir, "/data/compass-data/parquet_data");
    }

    #[test]
    fn dolt_config_default_values() {
        let config: AppConfig = toml::from_str("").unwrap();
        assert_eq!(
            config.dolt.investment_data_dir,
            "/data/compass-data/investment_data"
        );
        assert_eq!(
            config.dolt.compass_data_dir,
            "/data/compass-data/compass_data"
        );
    }

    #[test]
    fn dolt_config_overrides_from_toml() {
        let config: AppConfig = toml::from_str(
            r#"[dolt]
investment_data_dir = "/custom/investment"
compass_data_dir = "/custom/compass"
"#,
        )
        .unwrap();
        assert_eq!(config.dolt.investment_data_dir, "/custom/investment");
        assert_eq!(config.dolt.compass_data_dir, "/custom/compass");
    }

    #[test]
    fn watchlist_config_defaults_to_empty_symbols() {
        let watchlist = WatchlistConfig::default();
        assert!(watchlist.symbols.is_empty());
    }

    #[test]
    fn watchlist_config_parses_from_toml() {
        let watchlist: WatchlistConfig =
            toml::from_str("symbols = [\"000001\", \"600519\"]").unwrap();
        assert_eq!(
            watchlist.symbols,
            vec!["000001".to_string(), "600519".to_string()]
        );
    }

    #[test]
    fn watchlist_config_missing_symbols_key_defaults_empty() {
        let watchlist: WatchlistConfig = toml::from_str("").unwrap();
        assert!(watchlist.symbols.is_empty());
    }

    #[test]
    fn watchlist_config_serializes_to_toml() {
        let watchlist = WatchlistConfig {
            symbols: vec!["600519".to_string()],
        };
        let serialized = toml::to_string(&watchlist).unwrap();
        assert!(serialized.contains("symbols"), "serialized: {serialized}");
        assert!(serialized.contains("600519"));
        let parsed: WatchlistConfig = toml::from_str(&serialized).unwrap();
        assert_eq!(parsed.symbols, watchlist.symbols);
    }
}
