[package]
name = "compass-data"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "compass-data"
path = "src/main.rs"

[dependencies]
compass-core = { path = "../compass-core" }
chrono = { workspace = true }
clap = { workspace = true }
duckdb = { workspace = true }
egui-charts = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
httpmock = { workspace = true }
tempfile = { workspace = true }
