#!/usr/bin/env python3
"""A-share balance sheet collector (资产负债表).

Independent module — uses common.py for shared infrastructure.

Report:  RPT_F10_FINANCE_GBALANCE, 319 fields, filter column REPORT_DATE.
Default: 2020 onwards, all four quarterly periods.

Usage:
    uv run python fetch_balance_sheet.py              # full run (2020-now)
    uv run python fetch_balance_sheet.py --years 2024,2025
    uv run python fetch_balance_sheet.py --incremental
"""

import asyncio
import json
import sys
from datetime import date, datetime
from pathlib import Path

from common import (
    AsyncSession,
    Throttle,
    build_dates,
    csv_dir,
    dedupe_csv,
    fetch_by_update_date,
    fetch_paginated,
    import_replace_table,
    last_report_date,
    make_proxy_pool,
    normalize_update_date,
    update_date_anchor,
    write_csv,
)

REPORT_NAME = "RPT_F10_FINANCE_GBALANCE"
FILTER_COLUMN = "REPORT_DATE"  # underscore — different from RPT_LICO_FN_CPD
DOLT_TABLE = "fin_balance_sheet"
START_YEAR = 2020
INITIAL_UPDATE_ANCHOR = "2020-01-01"  # no-anchor first run: one full-history UPDATE_DATE pull

DDL = """\
CREATE TABLE IF NOT EXISTS fin_balance_sheet (
    symbol                           VARCHAR(20) NOT NULL,
    report_date                      DATE NOT NULL,
    SECUCODE                         VARCHAR(100),
    SECURITY_CODE                    VARCHAR(100),
    SECURITY_NAME_ABBR               VARCHAR(100),
    ORG_CODE                         VARCHAR(100),
    ORG_TYPE                         VARCHAR(100),
    REPORT_TYPE                      VARCHAR(100),
    REPORT_DATE_NAME                 VARCHAR(100),
    SECURITY_TYPE_CODE               VARCHAR(100),
    NOTICE_DATE                      VARCHAR(100),
    UPDATE_DATE                      VARCHAR(100),
    CURRENCY                         VARCHAR(100),
    ACCEPT_DEPOSIT_INTERBANK         DOUBLE,
    ACCOUNTS_PAYABLE                 DOUBLE,
    ACCOUNTS_RECE                    DOUBLE,
    ACCRUED_EXPENSE                  DOUBLE,
    ADVANCE_RECEIVABLES              DOUBLE,
    AGENT_TRADE_SECURITY             DOUBLE,
    AGENT_UNDERWRITE_SECURITY        DOUBLE,
    AMORTIZE_COST_FINASSET           DOUBLE,
    AMORTIZE_COST_FINLIAB            DOUBLE,
    AMORTIZE_COST_NCFINASSET         DOUBLE,
    AMORTIZE_COST_NCFINLIAB          DOUBLE,
    APPOINT_FVTPL_FINASSET           DOUBLE,
    APPOINT_FVTPL_FINLIAB            DOUBLE,
    ASSET_BALANCE                    DOUBLE,
    ASSET_OTHER                      DOUBLE,
    ASSIGN_CASH_DIVIDEND             DOUBLE,
    AVAILABLE_SALE_FINASSET          DOUBLE,
    BOND_PAYABLE                     DOUBLE,
    BORROW_FUND                      DOUBLE,
    BUY_RESALE_FINASSET              DOUBLE,
    CAPITAL_RESERVE                  DOUBLE,
    CIP                              DOUBLE,
    CONSUMPTIVE_BIOLOGICAL_ASSET     DOUBLE,
    CONTRACT_ASSET                   DOUBLE,
    CONTRACT_LIAB                    DOUBLE,
    CONVERT_DIFF                     DOUBLE,
    CREDITOR_INVEST                  DOUBLE,
    CURRENT_ASSET_BALANCE            DOUBLE,
    CURRENT_ASSET_OTHER              DOUBLE,
    CURRENT_LIAB_BALANCE             DOUBLE,
    CURRENT_LIAB_OTHER               DOUBLE,
    DEFER_INCOME                     DOUBLE,
    DEFER_INCOME_1YEAR               DOUBLE,
    DEFER_TAX_ASSET                  DOUBLE,
    DEFER_TAX_LIAB                   DOUBLE,
    DERIVE_FINASSET                  DOUBLE,
    DERIVE_FINLIAB                   DOUBLE,
    DEVELOP_EXPENSE                  DOUBLE,
    DIV_HOLDSALE_ASSET               DOUBLE,
    DIV_HOLDSALE_LIAB                DOUBLE,
    DIVIDEND_PAYABLE                 DOUBLE,
    DIVIDEND_RECE                    DOUBLE,
    EQUITY_BALANCE                   DOUBLE,
    EQUITY_OTHER                     DOUBLE,
    EXPORT_REFUND_RECE               DOUBLE,
    FEE_COMMISSION_PAYABLE           DOUBLE,
    FIN_FUND                         DOUBLE,
    FINANCE_RECE                     DOUBLE,
    FIXED_ASSET                      DOUBLE,
    FIXED_ASSET_DISPOSAL             DOUBLE,
    FVTOCI_FINASSET                  DOUBLE,
    FVTOCI_NCFINASSET                DOUBLE,
    FVTPL_FINASSET                   DOUBLE,
    FVTPL_FINLIAB                    DOUBLE,
    GENERAL_RISK_RESERVE             DOUBLE,
    GOODWILL                         DOUBLE,
    HOLD_MATURITY_INVEST             DOUBLE,
    HOLDSALE_ASSET                   DOUBLE,
    HOLDSALE_LIAB                    DOUBLE,
    INSURANCE_CONTRACT_RESERVE       DOUBLE,
    INTANGIBLE_ASSET                 DOUBLE,
    INTEREST_PAYABLE                 DOUBLE,
    INTEREST_RECE                    DOUBLE,
    INTERNAL_PAYABLE                 DOUBLE,
    INTERNAL_RECE                    DOUBLE,
    INVENTORY                        DOUBLE,
    INVEST_REALESTATE                DOUBLE,
    LEASE_LIAB                       DOUBLE,
    LEND_FUND                        DOUBLE,
    LIAB_BALANCE                     DOUBLE,
    LIAB_EQUITY_BALANCE              DOUBLE,
    LIAB_EQUITY_OTHER                DOUBLE,
    LIAB_OTHER                       DOUBLE,
    LOAN_ADVANCE                     DOUBLE,
    LOAN_PBC                         DOUBLE,
    LONG_EQUITY_INVEST               DOUBLE,
    LONG_LOAN                        DOUBLE,
    LONG_PAYABLE                     DOUBLE,
    LONG_PREPAID_EXPENSE             DOUBLE,
    LONG_RECE                        DOUBLE,
    LONG_STAFFSALARY_PAYABLE         DOUBLE,
    MINORITY_EQUITY                  DOUBLE,
    MONETARYFUNDS                    DOUBLE,
    NONCURRENT_ASSET_1YEAR           DOUBLE,
    NONCURRENT_ASSET_BALANCE         DOUBLE,
    NONCURRENT_ASSET_OTHER           DOUBLE,
    NONCURRENT_LIAB_1YEAR            DOUBLE,
    NONCURRENT_LIAB_BALANCE          DOUBLE,
    NONCURRENT_LIAB_OTHER            DOUBLE,
    NOTE_ACCOUNTS_PAYABLE            DOUBLE,
    NOTE_ACCOUNTS_RECE               DOUBLE,
    NOTE_PAYABLE                     DOUBLE,
    NOTE_RECE                        DOUBLE,
    OIL_GAS_ASSET                    DOUBLE,
    OTHER_COMPRE_INCOME              DOUBLE,
    OTHER_CREDITOR_INVEST            DOUBLE,
    OTHER_CURRENT_ASSET              DOUBLE,
    OTHER_CURRENT_LIAB               DOUBLE,
    OTHER_EQUITY_INVEST              DOUBLE,
    OTHER_EQUITY_OTHER               DOUBLE,
    OTHER_EQUITY_TOOL                DOUBLE,
    OTHER_NONCURRENT_ASSET           DOUBLE,
    OTHER_NONCURRENT_FINASSET        DOUBLE,
    OTHER_NONCURRENT_LIAB            DOUBLE,
    OTHER_PAYABLE                    DOUBLE,
    OTHER_RECE                       DOUBLE,
    PARENT_EQUITY_BALANCE            DOUBLE,
    PARENT_EQUITY_OTHER              DOUBLE,
    PERPETUAL_BOND                   DOUBLE,
    PERPETUAL_BOND_PAYBALE           DOUBLE,
    PREDICT_CURRENT_LIAB             DOUBLE,
    PREDICT_LIAB                     DOUBLE,
    PREFERRED_SHARES                 DOUBLE,
    PREFERRED_SHARES_PAYBALE         DOUBLE,
    PREMIUM_RECE                     DOUBLE,
    PREPAYMENT                       DOUBLE,
    PRODUCTIVE_BIOLOGY_ASSET         DOUBLE,
    PROJECT_MATERIAL                 DOUBLE,
    RC_RESERVE_RECE                  DOUBLE,
    REINSURE_PAYABLE                 DOUBLE,
    REINSURE_RECE                    DOUBLE,
    SELL_REPO_FINASSET               DOUBLE,
    SETTLE_EXCESS_RESERVE            DOUBLE,
    SHARE_CAPITAL                    DOUBLE,
    SHORT_BOND_PAYABLE               DOUBLE,
    SHORT_FIN_PAYABLE                DOUBLE,
    SHORT_LOAN                       DOUBLE,
    SPECIAL_PAYABLE                  DOUBLE,
    SPECIAL_RESERVE                  DOUBLE,
    STAFF_SALARY_PAYABLE             DOUBLE,
    SUBSIDY_RECE                     DOUBLE,
    SURPLUS_RESERVE                  DOUBLE,
    TAX_PAYABLE                      DOUBLE,
    TOTAL_ASSETS                     DOUBLE,
    TOTAL_CURRENT_ASSETS             DOUBLE,
    TOTAL_CURRENT_LIAB               DOUBLE,
    TOTAL_EQUITY                     DOUBLE,
    TOTAL_LIAB_EQUITY                DOUBLE,
    TOTAL_LIABILITIES                DOUBLE,
    TOTAL_NONCURRENT_ASSETS          DOUBLE,
    TOTAL_NONCURRENT_LIAB            DOUBLE,
    TOTAL_OTHER_PAYABLE              DOUBLE,
    TOTAL_OTHER_RECE                 DOUBLE,
    TOTAL_PARENT_EQUITY              DOUBLE,
    TRADE_FINASSET                   DOUBLE,
    TRADE_FINASSET_NOTFVTPL          DOUBLE,
    TRADE_FINLIAB                    DOUBLE,
    TRADE_FINLIAB_NOTFVTPL           DOUBLE,
    TREASURY_SHARES                  DOUBLE,
    UNASSIGN_RPOFIT                  DOUBLE,
    UNCONFIRM_INVEST_LOSS            DOUBLE,
    USERIGHT_ASSET                   DOUBLE,
    ACCEPT_DEPOSIT_INTERBANK_YOY     DOUBLE,
    ACCOUNTS_PAYABLE_YOY             DOUBLE,
    ACCOUNTS_RECE_YOY                DOUBLE,
    ACCRUED_EXPENSE_YOY              DOUBLE,
    ADVANCE_RECEIVABLES_YOY          DOUBLE,
    AGENT_TRADE_SECURITY_YOY         DOUBLE,
    AGENT_UNDERWRITE_SECURITY_YOY    DOUBLE,
    AMORTIZE_COST_FINASSET_YOY       DOUBLE,
    AMORTIZE_COST_FINLIAB_YOY        DOUBLE,
    AMORTIZE_COST_NCFINASSET_YOY     DOUBLE,
    AMORTIZE_COST_NCFINLIAB_YOY      DOUBLE,
    APPOINT_FVTPL_FINASSET_YOY       DOUBLE,
    APPOINT_FVTPL_FINLIAB_YOY        DOUBLE,
    ASSET_BALANCE_YOY                DOUBLE,
    ASSET_OTHER_YOY                  DOUBLE,
    ASSIGN_CASH_DIVIDEND_YOY         DOUBLE,
    AVAILABLE_SALE_FINASSET_YOY      DOUBLE,
    BOND_PAYABLE_YOY                 DOUBLE,
    BORROW_FUND_YOY                  DOUBLE,
    BUY_RESALE_FINASSET_YOY          DOUBLE,
    CAPITAL_RESERVE_YOY              DOUBLE,
    CIP_YOY                          DOUBLE,
    CONSUMPTIVE_BIOLOGICAL_ASSET_YOY DOUBLE,
    CONTRACT_ASSET_YOY               DOUBLE,
    CONTRACT_LIAB_YOY                DOUBLE,
    CONVERT_DIFF_YOY                 DOUBLE,
    CREDITOR_INVEST_YOY              DOUBLE,
    CURRENT_ASSET_BALANCE_YOY        DOUBLE,
    CURRENT_ASSET_OTHER_YOY          DOUBLE,
    CURRENT_LIAB_BALANCE_YOY         DOUBLE,
    CURRENT_LIAB_OTHER_YOY           DOUBLE,
    DEFER_INCOME_1YEAR_YOY           DOUBLE,
    DEFER_INCOME_YOY                 DOUBLE,
    DEFER_TAX_ASSET_YOY              DOUBLE,
    DEFER_TAX_LIAB_YOY               DOUBLE,
    DERIVE_FINASSET_YOY              DOUBLE,
    DERIVE_FINLIAB_YOY               DOUBLE,
    DEVELOP_EXPENSE_YOY              DOUBLE,
    DIV_HOLDSALE_ASSET_YOY           DOUBLE,
    DIV_HOLDSALE_LIAB_YOY            DOUBLE,
    DIVIDEND_PAYABLE_YOY             DOUBLE,
    DIVIDEND_RECE_YOY                DOUBLE,
    EQUITY_BALANCE_YOY               DOUBLE,
    EQUITY_OTHER_YOY                 DOUBLE,
    EXPORT_REFUND_RECE_YOY           DOUBLE,
    FEE_COMMISSION_PAYABLE_YOY       DOUBLE,
    FIN_FUND_YOY                     DOUBLE,
    FINANCE_RECE_YOY                 DOUBLE,
    FIXED_ASSET_DISPOSAL_YOY         DOUBLE,
    FIXED_ASSET_YOY                  DOUBLE,
    FVTOCI_FINASSET_YOY              DOUBLE,
    FVTOCI_NCFINASSET_YOY            DOUBLE,
    FVTPL_FINASSET_YOY               DOUBLE,
    FVTPL_FINLIAB_YOY                DOUBLE,
    GENERAL_RISK_RESERVE_YOY         DOUBLE,
    GOODWILL_YOY                     DOUBLE,
    HOLD_MATURITY_INVEST_YOY         DOUBLE,
    HOLDSALE_ASSET_YOY               DOUBLE,
    HOLDSALE_LIAB_YOY                DOUBLE,
    INSURANCE_CONTRACT_RESERVE_YOY   DOUBLE,
    INTANGIBLE_ASSET_YOY             DOUBLE,
    INTEREST_PAYABLE_YOY             DOUBLE,
    INTEREST_RECE_YOY                DOUBLE,
    INTERNAL_PAYABLE_YOY             DOUBLE,
    INTERNAL_RECE_YOY                DOUBLE,
    INVENTORY_YOY                    DOUBLE,
    INVEST_REALESTATE_YOY            DOUBLE,
    LEASE_LIAB_YOY                   DOUBLE,
    LEND_FUND_YOY                    DOUBLE,
    LIAB_BALANCE_YOY                 DOUBLE,
    LIAB_EQUITY_BALANCE_YOY          DOUBLE,
    LIAB_EQUITY_OTHER_YOY            DOUBLE,
    LIAB_OTHER_YOY                   DOUBLE,
    LOAN_ADVANCE_YOY                 DOUBLE,
    LOAN_PBC_YOY                     DOUBLE,
    LONG_EQUITY_INVEST_YOY           DOUBLE,
    LONG_LOAN_YOY                    DOUBLE,
    LONG_PAYABLE_YOY                 DOUBLE,
    LONG_PREPAID_EXPENSE_YOY         DOUBLE,
    LONG_RECE_YOY                    DOUBLE,
    LONG_STAFFSALARY_PAYABLE_YOY     DOUBLE,
    MINORITY_EQUITY_YOY              DOUBLE,
    MONETARYFUNDS_YOY                DOUBLE,
    NONCURRENT_ASSET_1YEAR_YOY       DOUBLE,
    NONCURRENT_ASSET_BALANCE_YOY     DOUBLE,
    NONCURRENT_ASSET_OTHER_YOY       DOUBLE,
    NONCURRENT_LIAB_1YEAR_YOY        DOUBLE,
    NONCURRENT_LIAB_BALANCE_YOY      DOUBLE,
    NONCURRENT_LIAB_OTHER_YOY        DOUBLE,
    NOTE_ACCOUNTS_PAYABLE_YOY        DOUBLE,
    NOTE_ACCOUNTS_RECE_YOY           DOUBLE,
    NOTE_PAYABLE_YOY                 DOUBLE,
    NOTE_RECE_YOY                    DOUBLE,
    OIL_GAS_ASSET_YOY                DOUBLE,
    OTHER_COMPRE_INCOME_YOY          DOUBLE,
    OTHER_CREDITOR_INVEST_YOY        DOUBLE,
    OTHER_CURRENT_ASSET_YOY          DOUBLE,
    OTHER_CURRENT_LIAB_YOY           DOUBLE,
    OTHER_EQUITY_INVEST_YOY          DOUBLE,
    OTHER_EQUITY_OTHER_YOY           DOUBLE,
    OTHER_EQUITY_TOOL_YOY            DOUBLE,
    OTHER_NONCURRENT_ASSET_YOY       DOUBLE,
    OTHER_NONCURRENT_FINASSET_YOY    DOUBLE,
    OTHER_NONCURRENT_LIAB_YOY        DOUBLE,
    OTHER_PAYABLE_YOY                DOUBLE,
    OTHER_RECE_YOY                   DOUBLE,
    PARENT_EQUITY_BALANCE_YOY        DOUBLE,
    PARENT_EQUITY_OTHER_YOY          DOUBLE,
    PERPETUAL_BOND_PAYBALE_YOY       DOUBLE,
    PERPETUAL_BOND_YOY               DOUBLE,
    PREDICT_CURRENT_LIAB_YOY         DOUBLE,
    PREDICT_LIAB_YOY                 DOUBLE,
    PREFERRED_SHARES_PAYBALE_YOY     DOUBLE,
    PREFERRED_SHARES_YOY             DOUBLE,
    PREMIUM_RECE_YOY                 DOUBLE,
    PREPAYMENT_YOY                   DOUBLE,
    PRODUCTIVE_BIOLOGY_ASSET_YOY     DOUBLE,
    PROJECT_MATERIAL_YOY             DOUBLE,
    RC_RESERVE_RECE_YOY              DOUBLE,
    REINSURE_PAYABLE_YOY             DOUBLE,
    REINSURE_RECE_YOY                DOUBLE,
    SELL_REPO_FINASSET_YOY           DOUBLE,
    SETTLE_EXCESS_RESERVE_YOY        DOUBLE,
    SHARE_CAPITAL_YOY                DOUBLE,
    SHORT_BOND_PAYABLE_YOY           DOUBLE,
    SHORT_FIN_PAYABLE_YOY            DOUBLE,
    SHORT_LOAN_YOY                   DOUBLE,
    SPECIAL_PAYABLE_YOY              DOUBLE,
    SPECIAL_RESERVE_YOY              DOUBLE,
    STAFF_SALARY_PAYABLE_YOY         DOUBLE,
    SUBSIDY_RECE_YOY                 DOUBLE,
    SURPLUS_RESERVE_YOY              DOUBLE,
    TAX_PAYABLE_YOY                  DOUBLE,
    TOTAL_ASSETS_YOY                 DOUBLE,
    TOTAL_CURRENT_ASSETS_YOY         DOUBLE,
    TOTAL_CURRENT_LIAB_YOY           DOUBLE,
    TOTAL_EQUITY_YOY                 DOUBLE,
    TOTAL_LIAB_EQUITY_YOY            DOUBLE,
    TOTAL_LIABILITIES_YOY            DOUBLE,
    TOTAL_NONCURRENT_ASSETS_YOY      DOUBLE,
    TOTAL_NONCURRENT_LIAB_YOY        DOUBLE,
    TOTAL_OTHER_PAYABLE_YOY          DOUBLE,
    TOTAL_OTHER_RECE_YOY             DOUBLE,
    TOTAL_PARENT_EQUITY_YOY          DOUBLE,
    TRADE_FINASSET_NOTFVTPL_YOY      DOUBLE,
    TRADE_FINASSET_YOY               DOUBLE,
    TRADE_FINLIAB_NOTFVTPL_YOY       DOUBLE,
    TRADE_FINLIAB_YOY                DOUBLE,
    TREASURY_SHARES_YOY              DOUBLE,
    UNASSIGN_RPOFIT_YOY              DOUBLE,
    UNCONFIRM_INVEST_LOSS_YOY        DOUBLE,
    USERIGHT_ASSET_YOY               DOUBLE,
    OPINION_TYPE                     VARCHAR(100),
    OSOPINION_TYPE                   DOUBLE,
    LISTING_STATE                    VARCHAR(100),
    PRIMARY KEY (symbol, report_date)
)
"""

COLS = "SECUCODE, SECURITY_CODE, SECURITY_NAME_ABBR, ORG_CODE, ORG_TYPE, REPORT_TYPE, REPORT_DATE_NAME, SECURITY_TYPE_CODE, NOTICE_DATE, UPDATE_DATE, CURRENCY, ACCEPT_DEPOSIT_INTERBANK, ACCOUNTS_PAYABLE, ACCOUNTS_RECE, ACCRUED_EXPENSE, ADVANCE_RECEIVABLES, AGENT_TRADE_SECURITY, AGENT_UNDERWRITE_SECURITY, AMORTIZE_COST_FINASSET, AMORTIZE_COST_FINLIAB, AMORTIZE_COST_NCFINASSET, AMORTIZE_COST_NCFINLIAB, APPOINT_FVTPL_FINASSET, APPOINT_FVTPL_FINLIAB, ASSET_BALANCE, ASSET_OTHER, ASSIGN_CASH_DIVIDEND, AVAILABLE_SALE_FINASSET, BOND_PAYABLE, BORROW_FUND, BUY_RESALE_FINASSET, CAPITAL_RESERVE, CIP, CONSUMPTIVE_BIOLOGICAL_ASSET, CONTRACT_ASSET, CONTRACT_LIAB, CONVERT_DIFF, CREDITOR_INVEST, CURRENT_ASSET_BALANCE, CURRENT_ASSET_OTHER, CURRENT_LIAB_BALANCE, CURRENT_LIAB_OTHER, DEFER_INCOME, DEFER_INCOME_1YEAR, DEFER_TAX_ASSET, DEFER_TAX_LIAB, DERIVE_FINASSET, DERIVE_FINLIAB, DEVELOP_EXPENSE, DIV_HOLDSALE_ASSET, DIV_HOLDSALE_LIAB, DIVIDEND_PAYABLE, DIVIDEND_RECE, EQUITY_BALANCE, EQUITY_OTHER, EXPORT_REFUND_RECE, FEE_COMMISSION_PAYABLE, FIN_FUND, FINANCE_RECE, FIXED_ASSET, FIXED_ASSET_DISPOSAL, FVTOCI_FINASSET, FVTOCI_NCFINASSET, FVTPL_FINASSET, FVTPL_FINLIAB, GENERAL_RISK_RESERVE, GOODWILL, HOLD_MATURITY_INVEST, HOLDSALE_ASSET, HOLDSALE_LIAB, INSURANCE_CONTRACT_RESERVE, INTANGIBLE_ASSET, INTEREST_PAYABLE, INTEREST_RECE, INTERNAL_PAYABLE, INTERNAL_RECE, INVENTORY, INVEST_REALESTATE, LEASE_LIAB, LEND_FUND, LIAB_BALANCE, LIAB_EQUITY_BALANCE, LIAB_EQUITY_OTHER, LIAB_OTHER, LOAN_ADVANCE, LOAN_PBC, LONG_EQUITY_INVEST, LONG_LOAN, LONG_PAYABLE, LONG_PREPAID_EXPENSE, LONG_RECE, LONG_STAFFSALARY_PAYABLE, MINORITY_EQUITY, MONETARYFUNDS, NONCURRENT_ASSET_1YEAR, NONCURRENT_ASSET_BALANCE, NONCURRENT_ASSET_OTHER, NONCURRENT_LIAB_1YEAR, NONCURRENT_LIAB_BALANCE, NONCURRENT_LIAB_OTHER, NOTE_ACCOUNTS_PAYABLE, NOTE_ACCOUNTS_RECE, NOTE_PAYABLE, NOTE_RECE, OIL_GAS_ASSET, OTHER_COMPRE_INCOME, OTHER_CREDITOR_INVEST, OTHER_CURRENT_ASSET, OTHER_CURRENT_LIAB, OTHER_EQUITY_INVEST, OTHER_EQUITY_OTHER, OTHER_EQUITY_TOOL, OTHER_NONCURRENT_ASSET, OTHER_NONCURRENT_FINASSET, OTHER_NONCURRENT_LIAB, OTHER_PAYABLE, OTHER_RECE, PARENT_EQUITY_BALANCE, PARENT_EQUITY_OTHER, PERPETUAL_BOND, PERPETUAL_BOND_PAYBALE, PREDICT_CURRENT_LIAB, PREDICT_LIAB, PREFERRED_SHARES, PREFERRED_SHARES_PAYBALE, PREMIUM_RECE, PREPAYMENT, PRODUCTIVE_BIOLOGY_ASSET, PROJECT_MATERIAL, RC_RESERVE_RECE, REINSURE_PAYABLE, REINSURE_RECE, SELL_REPO_FINASSET, SETTLE_EXCESS_RESERVE, SHARE_CAPITAL, SHORT_BOND_PAYABLE, SHORT_FIN_PAYABLE, SHORT_LOAN, SPECIAL_PAYABLE, SPECIAL_RESERVE, STAFF_SALARY_PAYABLE, SUBSIDY_RECE, SURPLUS_RESERVE, TAX_PAYABLE, TOTAL_ASSETS, TOTAL_CURRENT_ASSETS, TOTAL_CURRENT_LIAB, TOTAL_EQUITY, TOTAL_LIAB_EQUITY, TOTAL_LIABILITIES, TOTAL_NONCURRENT_ASSETS, TOTAL_NONCURRENT_LIAB, TOTAL_OTHER_PAYABLE, TOTAL_OTHER_RECE, TOTAL_PARENT_EQUITY, TRADE_FINASSET, TRADE_FINASSET_NOTFVTPL, TRADE_FINLIAB, TRADE_FINLIAB_NOTFVTPL, TREASURY_SHARES, UNASSIGN_RPOFIT, UNCONFIRM_INVEST_LOSS, USERIGHT_ASSET, ACCEPT_DEPOSIT_INTERBANK_YOY, ACCOUNTS_PAYABLE_YOY, ACCOUNTS_RECE_YOY, ACCRUED_EXPENSE_YOY, ADVANCE_RECEIVABLES_YOY, AGENT_TRADE_SECURITY_YOY, AGENT_UNDERWRITE_SECURITY_YOY, AMORTIZE_COST_FINASSET_YOY, AMORTIZE_COST_FINLIAB_YOY, AMORTIZE_COST_NCFINASSET_YOY, AMORTIZE_COST_NCFINLIAB_YOY, APPOINT_FVTPL_FINASSET_YOY, APPOINT_FVTPL_FINLIAB_YOY, ASSET_BALANCE_YOY, ASSET_OTHER_YOY, ASSIGN_CASH_DIVIDEND_YOY, AVAILABLE_SALE_FINASSET_YOY, BOND_PAYABLE_YOY, BORROW_FUND_YOY, BUY_RESALE_FINASSET_YOY, CAPITAL_RESERVE_YOY, CIP_YOY, CONSUMPTIVE_BIOLOGICAL_ASSET_YOY, CONTRACT_ASSET_YOY, CONTRACT_LIAB_YOY, CONVERT_DIFF_YOY, CREDITOR_INVEST_YOY, CURRENT_ASSET_BALANCE_YOY, CURRENT_ASSET_OTHER_YOY, CURRENT_LIAB_BALANCE_YOY, CURRENT_LIAB_OTHER_YOY, DEFER_INCOME_1YEAR_YOY, DEFER_INCOME_YOY, DEFER_TAX_ASSET_YOY, DEFER_TAX_LIAB_YOY, DERIVE_FINASSET_YOY, DERIVE_FINLIAB_YOY, DEVELOP_EXPENSE_YOY, DIV_HOLDSALE_ASSET_YOY, DIV_HOLDSALE_LIAB_YOY, DIVIDEND_PAYABLE_YOY, DIVIDEND_RECE_YOY, EQUITY_BALANCE_YOY, EQUITY_OTHER_YOY, EXPORT_REFUND_RECE_YOY, FEE_COMMISSION_PAYABLE_YOY, FIN_FUND_YOY, FINANCE_RECE_YOY, FIXED_ASSET_DISPOSAL_YOY, FIXED_ASSET_YOY, FVTOCI_FINASSET_YOY, FVTOCI_NCFINASSET_YOY, FVTPL_FINASSET_YOY, FVTPL_FINLIAB_YOY, GENERAL_RISK_RESERVE_YOY, GOODWILL_YOY, HOLD_MATURITY_INVEST_YOY, HOLDSALE_ASSET_YOY, HOLDSALE_LIAB_YOY, INSURANCE_CONTRACT_RESERVE_YOY, INTANGIBLE_ASSET_YOY, INTEREST_PAYABLE_YOY, INTEREST_RECE_YOY, INTERNAL_PAYABLE_YOY, INTERNAL_RECE_YOY, INVENTORY_YOY, INVEST_REALESTATE_YOY, LEASE_LIAB_YOY, LEND_FUND_YOY, LIAB_BALANCE_YOY, LIAB_EQUITY_BALANCE_YOY, LIAB_EQUITY_OTHER_YOY, LIAB_OTHER_YOY, LOAN_ADVANCE_YOY, LOAN_PBC_YOY, LONG_EQUITY_INVEST_YOY, LONG_LOAN_YOY, LONG_PAYABLE_YOY, LONG_PREPAID_EXPENSE_YOY, LONG_RECE_YOY, LONG_STAFFSALARY_PAYABLE_YOY, MINORITY_EQUITY_YOY, MONETARYFUNDS_YOY, NONCURRENT_ASSET_1YEAR_YOY, NONCURRENT_ASSET_BALANCE_YOY, NONCURRENT_ASSET_OTHER_YOY, NONCURRENT_LIAB_1YEAR_YOY, NONCURRENT_LIAB_BALANCE_YOY, NONCURRENT_LIAB_OTHER_YOY, NOTE_ACCOUNTS_PAYABLE_YOY, NOTE_ACCOUNTS_RECE_YOY, NOTE_PAYABLE_YOY, NOTE_RECE_YOY, OIL_GAS_ASSET_YOY, OTHER_COMPRE_INCOME_YOY, OTHER_CREDITOR_INVEST_YOY, OTHER_CURRENT_ASSET_YOY, OTHER_CURRENT_LIAB_YOY, OTHER_EQUITY_INVEST_YOY, OTHER_EQUITY_OTHER_YOY, OTHER_EQUITY_TOOL_YOY, OTHER_NONCURRENT_ASSET_YOY, OTHER_NONCURRENT_FINASSET_YOY, OTHER_NONCURRENT_LIAB_YOY, OTHER_PAYABLE_YOY, OTHER_RECE_YOY, PARENT_EQUITY_BALANCE_YOY, PARENT_EQUITY_OTHER_YOY, PERPETUAL_BOND_PAYBALE_YOY, PERPETUAL_BOND_YOY, PREDICT_CURRENT_LIAB_YOY, PREDICT_LIAB_YOY, PREFERRED_SHARES_PAYBALE_YOY, PREFERRED_SHARES_YOY, PREMIUM_RECE_YOY, PREPAYMENT_YOY, PRODUCTIVE_BIOLOGY_ASSET_YOY, PROJECT_MATERIAL_YOY, RC_RESERVE_RECE_YOY, REINSURE_PAYABLE_YOY, REINSURE_RECE_YOY, SELL_REPO_FINASSET_YOY, SETTLE_EXCESS_RESERVE_YOY, SHARE_CAPITAL_YOY, SHORT_BOND_PAYABLE_YOY, SHORT_FIN_PAYABLE_YOY, SHORT_LOAN_YOY, SPECIAL_PAYABLE_YOY, SPECIAL_RESERVE_YOY, STAFF_SALARY_PAYABLE_YOY, SUBSIDY_RECE_YOY, SURPLUS_RESERVE_YOY, TAX_PAYABLE_YOY, TOTAL_ASSETS_YOY, TOTAL_CURRENT_ASSETS_YOY, TOTAL_CURRENT_LIAB_YOY, TOTAL_EQUITY_YOY, TOTAL_LIAB_EQUITY_YOY, TOTAL_LIABILITIES_YOY, TOTAL_NONCURRENT_ASSETS_YOY, TOTAL_NONCURRENT_LIAB_YOY, TOTAL_OTHER_PAYABLE_YOY, TOTAL_OTHER_RECE_YOY, TOTAL_PARENT_EQUITY_YOY, TRADE_FINASSET_NOTFVTPL_YOY, TRADE_FINASSET_YOY, TRADE_FINLIAB_NOTFVTPL_YOY, TRADE_FINLIAB_YOY, TREASURY_SHARES_YOY, UNASSIGN_RPOFIT_YOY, UNCONFIRM_INVEST_LOSS_YOY, USERIGHT_ASSET_YOY, OPINION_TYPE, OSOPINION_TYPE, LISTING_STATE"

# Text columns to TRIM on import (issue #235): user-visible string fields that
# can carry leading/trailing whitespace from EastMoney. Identifier/date columns
# (SECUCODE, SECURITY_CODE, SECURITY_TYPE_CODE, ORG_CODE, NOTICE_DATE,
# UPDATE_DATE) are intentionally left untrimmed.
_TRIM_TEXT_COLS = frozenset({
    "SECURITY_NAME_ABBR", "ORG_TYPE", "REPORT_TYPE", "REPORT_DATE_NAME",
    "CURRENCY", "OPINION_TYPE", "LISTING_STATE",
})


def trim_select_cols() -> str:
    """SELECT-side column list with text columns wrapped in TRIM(col) AS col.

    Keeps the same order and names as COLS so the INSERT column list
    ({COLS}) aligns positionally; numeric columns pass through untouched.
    """
    return ", ".join(
        f"TRIM({col}) AS {col}" if col in _TRIM_TEXT_COLS else col
        for col in COLS.split(", ")
    )


def _upsert_select_cols() -> str:
    """SELECT-side aliased column list for the merge/ODKU import.

    Each COLS column gets a unique ``_<COL>`` alias so the ODKU clause can
    reference the source value without the Dolt-2.2.3-incompatible qualified
    source refs or ``VALUES()`` (see main.py::_import_fin_indicators).
    """
    return ", ".join(
        f"TRIM({col}) AS _{col}" if col in _TRIM_TEXT_COLS else f"{col} AS _{col}"
        for col in COLS.split(", ")
    )


def _upsert_updates() -> str:
    """ODKU update list: every non-PK COLS column is overwritten by its alias."""
    return ", ".join(f"{col}=_{col}" for col in COLS.split(", "))


# Wide temp-table schema: Dolt's `-c` CSV import inference caps row size at
# 65504 bytes, which a 319-column CSV overflows — create the temp table
# explicitly and import with `-u` (see common.py dolt_table_import).
_TMP_BS_DDL = """\
CREATE TABLE _tmp_bs (
    SECUCODE                         VARCHAR(100),
    SECURITY_CODE                    VARCHAR(100),
    SECURITY_NAME_ABBR               VARCHAR(100),
    ORG_CODE                         VARCHAR(100),
    ORG_TYPE                         VARCHAR(100),
    REPORT_DATE                      VARCHAR(100),
    REPORT_TYPE                      VARCHAR(100),
    REPORT_DATE_NAME                 VARCHAR(100),
    SECURITY_TYPE_CODE               VARCHAR(100),
    NOTICE_DATE                      VARCHAR(100),
    UPDATE_DATE                      VARCHAR(100),
    CURRENCY                         VARCHAR(100),
    ACCEPT_DEPOSIT_INTERBANK         DOUBLE,
    ACCOUNTS_PAYABLE                 DOUBLE,
    ACCOUNTS_RECE                    DOUBLE,
    ACCRUED_EXPENSE                  DOUBLE,
    ADVANCE_RECEIVABLES              DOUBLE,
    AGENT_TRADE_SECURITY             DOUBLE,
    AGENT_UNDERWRITE_SECURITY        DOUBLE,
    AMORTIZE_COST_FINASSET           DOUBLE,
    AMORTIZE_COST_FINLIAB            DOUBLE,
    AMORTIZE_COST_NCFINASSET         DOUBLE,
    AMORTIZE_COST_NCFINLIAB          DOUBLE,
    APPOINT_FVTPL_FINASSET           DOUBLE,
    APPOINT_FVTPL_FINLIAB            DOUBLE,
    ASSET_BALANCE                    DOUBLE,
    ASSET_OTHER                      DOUBLE,
    ASSIGN_CASH_DIVIDEND             DOUBLE,
    AVAILABLE_SALE_FINASSET          DOUBLE,
    BOND_PAYABLE                     DOUBLE,
    BORROW_FUND                      DOUBLE,
    BUY_RESALE_FINASSET              DOUBLE,
    CAPITAL_RESERVE                  DOUBLE,
    CIP                              DOUBLE,
    CONSUMPTIVE_BIOLOGICAL_ASSET     DOUBLE,
    CONTRACT_ASSET                   DOUBLE,
    CONTRACT_LIAB                    DOUBLE,
    CONVERT_DIFF                     DOUBLE,
    CREDITOR_INVEST                  DOUBLE,
    CURRENT_ASSET_BALANCE            DOUBLE,
    CURRENT_ASSET_OTHER              DOUBLE,
    CURRENT_LIAB_BALANCE             DOUBLE,
    CURRENT_LIAB_OTHER               DOUBLE,
    DEFER_INCOME                     DOUBLE,
    DEFER_INCOME_1YEAR               DOUBLE,
    DEFER_TAX_ASSET                  DOUBLE,
    DEFER_TAX_LIAB                   DOUBLE,
    DERIVE_FINASSET                  DOUBLE,
    DERIVE_FINLIAB                   DOUBLE,
    DEVELOP_EXPENSE                  DOUBLE,
    DIV_HOLDSALE_ASSET               DOUBLE,
    DIV_HOLDSALE_LIAB                DOUBLE,
    DIVIDEND_PAYABLE                 DOUBLE,
    DIVIDEND_RECE                    DOUBLE,
    EQUITY_BALANCE                   DOUBLE,
    EQUITY_OTHER                     DOUBLE,
    EXPORT_REFUND_RECE               DOUBLE,
    FEE_COMMISSION_PAYABLE           DOUBLE,
    FIN_FUND                         DOUBLE,
    FINANCE_RECE                     DOUBLE,
    FIXED_ASSET                      DOUBLE,
    FIXED_ASSET_DISPOSAL             DOUBLE,
    FVTOCI_FINASSET                  DOUBLE,
    FVTOCI_NCFINASSET                DOUBLE,
    FVTPL_FINASSET                   DOUBLE,
    FVTPL_FINLIAB                    DOUBLE,
    GENERAL_RISK_RESERVE             DOUBLE,
    GOODWILL                         DOUBLE,
    HOLD_MATURITY_INVEST             DOUBLE,
    HOLDSALE_ASSET                   DOUBLE,
    HOLDSALE_LIAB                    DOUBLE,
    INSURANCE_CONTRACT_RESERVE       DOUBLE,
    INTANGIBLE_ASSET                 DOUBLE,
    INTEREST_PAYABLE                 DOUBLE,
    INTEREST_RECE                    DOUBLE,
    INTERNAL_PAYABLE                 DOUBLE,
    INTERNAL_RECE                    DOUBLE,
    INVENTORY                        DOUBLE,
    INVEST_REALESTATE                DOUBLE,
    LEASE_LIAB                       DOUBLE,
    LEND_FUND                        DOUBLE,
    LIAB_BALANCE                     DOUBLE,
    LIAB_EQUITY_BALANCE              DOUBLE,
    LIAB_EQUITY_OTHER                DOUBLE,
    LIAB_OTHER                       DOUBLE,
    LOAN_ADVANCE                     DOUBLE,
    LOAN_PBC                         DOUBLE,
    LONG_EQUITY_INVEST               DOUBLE,
    LONG_LOAN                        DOUBLE,
    LONG_PAYABLE                     DOUBLE,
    LONG_PREPAID_EXPENSE             DOUBLE,
    LONG_RECE                        DOUBLE,
    LONG_STAFFSALARY_PAYABLE         DOUBLE,
    MINORITY_EQUITY                  DOUBLE,
    MONETARYFUNDS                    DOUBLE,
    NONCURRENT_ASSET_1YEAR           DOUBLE,
    NONCURRENT_ASSET_BALANCE         DOUBLE,
    NONCURRENT_ASSET_OTHER           DOUBLE,
    NONCURRENT_LIAB_1YEAR            DOUBLE,
    NONCURRENT_LIAB_BALANCE          DOUBLE,
    NONCURRENT_LIAB_OTHER            DOUBLE,
    NOTE_ACCOUNTS_PAYABLE            DOUBLE,
    NOTE_ACCOUNTS_RECE               DOUBLE,
    NOTE_PAYABLE                     DOUBLE,
    NOTE_RECE                        DOUBLE,
    OIL_GAS_ASSET                    DOUBLE,
    OTHER_COMPRE_INCOME              DOUBLE,
    OTHER_CREDITOR_INVEST            DOUBLE,
    OTHER_CURRENT_ASSET              DOUBLE,
    OTHER_CURRENT_LIAB               DOUBLE,
    OTHER_EQUITY_INVEST              DOUBLE,
    OTHER_EQUITY_OTHER               DOUBLE,
    OTHER_EQUITY_TOOL                DOUBLE,
    OTHER_NONCURRENT_ASSET           DOUBLE,
    OTHER_NONCURRENT_FINASSET        DOUBLE,
    OTHER_NONCURRENT_LIAB            DOUBLE,
    OTHER_PAYABLE                    DOUBLE,
    OTHER_RECE                       DOUBLE,
    PARENT_EQUITY_BALANCE            DOUBLE,
    PARENT_EQUITY_OTHER              DOUBLE,
    PERPETUAL_BOND                   DOUBLE,
    PERPETUAL_BOND_PAYBALE           DOUBLE,
    PREDICT_CURRENT_LIAB             DOUBLE,
    PREDICT_LIAB                     DOUBLE,
    PREFERRED_SHARES                 DOUBLE,
    PREFERRED_SHARES_PAYBALE         DOUBLE,
    PREMIUM_RECE                     DOUBLE,
    PREPAYMENT                       DOUBLE,
    PRODUCTIVE_BIOLOGY_ASSET         DOUBLE,
    PROJECT_MATERIAL                 DOUBLE,
    RC_RESERVE_RECE                  DOUBLE,
    REINSURE_PAYABLE                 DOUBLE,
    REINSURE_RECE                    DOUBLE,
    SELL_REPO_FINASSET               DOUBLE,
    SETTLE_EXCESS_RESERVE            DOUBLE,
    SHARE_CAPITAL                    DOUBLE,
    SHORT_BOND_PAYABLE               DOUBLE,
    SHORT_FIN_PAYABLE                DOUBLE,
    SHORT_LOAN                       DOUBLE,
    SPECIAL_PAYABLE                  DOUBLE,
    SPECIAL_RESERVE                  DOUBLE,
    STAFF_SALARY_PAYABLE             DOUBLE,
    SUBSIDY_RECE                     DOUBLE,
    SURPLUS_RESERVE                  DOUBLE,
    TAX_PAYABLE                      DOUBLE,
    TOTAL_ASSETS                     DOUBLE,
    TOTAL_CURRENT_ASSETS             DOUBLE,
    TOTAL_CURRENT_LIAB               DOUBLE,
    TOTAL_EQUITY                     DOUBLE,
    TOTAL_LIAB_EQUITY                DOUBLE,
    TOTAL_LIABILITIES                DOUBLE,
    TOTAL_NONCURRENT_ASSETS          DOUBLE,
    TOTAL_NONCURRENT_LIAB            DOUBLE,
    TOTAL_OTHER_PAYABLE              DOUBLE,
    TOTAL_OTHER_RECE                 DOUBLE,
    TOTAL_PARENT_EQUITY              DOUBLE,
    TRADE_FINASSET                   DOUBLE,
    TRADE_FINASSET_NOTFVTPL          DOUBLE,
    TRADE_FINLIAB                    DOUBLE,
    TRADE_FINLIAB_NOTFVTPL           DOUBLE,
    TREASURY_SHARES                  DOUBLE,
    UNASSIGN_RPOFIT                  DOUBLE,
    UNCONFIRM_INVEST_LOSS            DOUBLE,
    USERIGHT_ASSET                   DOUBLE,
    ACCEPT_DEPOSIT_INTERBANK_YOY     DOUBLE,
    ACCOUNTS_PAYABLE_YOY             DOUBLE,
    ACCOUNTS_RECE_YOY                DOUBLE,
    ACCRUED_EXPENSE_YOY              DOUBLE,
    ADVANCE_RECEIVABLES_YOY          DOUBLE,
    AGENT_TRADE_SECURITY_YOY         DOUBLE,
    AGENT_UNDERWRITE_SECURITY_YOY    DOUBLE,
    AMORTIZE_COST_FINASSET_YOY       DOUBLE,
    AMORTIZE_COST_FINLIAB_YOY        DOUBLE,
    AMORTIZE_COST_NCFINASSET_YOY     DOUBLE,
    AMORTIZE_COST_NCFINLIAB_YOY      DOUBLE,
    APPOINT_FVTPL_FINASSET_YOY       DOUBLE,
    APPOINT_FVTPL_FINLIAB_YOY        DOUBLE,
    ASSET_BALANCE_YOY                DOUBLE,
    ASSET_OTHER_YOY                  DOUBLE,
    ASSIGN_CASH_DIVIDEND_YOY         DOUBLE,
    AVAILABLE_SALE_FINASSET_YOY      DOUBLE,
    BOND_PAYABLE_YOY                 DOUBLE,
    BORROW_FUND_YOY                  DOUBLE,
    BUY_RESALE_FINASSET_YOY          DOUBLE,
    CAPITAL_RESERVE_YOY              DOUBLE,
    CIP_YOY                          DOUBLE,
    CONSUMPTIVE_BIOLOGICAL_ASSET_YOY DOUBLE,
    CONTRACT_ASSET_YOY               DOUBLE,
    CONTRACT_LIAB_YOY                DOUBLE,
    CONVERT_DIFF_YOY                 DOUBLE,
    CREDITOR_INVEST_YOY              DOUBLE,
    CURRENT_ASSET_BALANCE_YOY        DOUBLE,
    CURRENT_ASSET_OTHER_YOY          DOUBLE,
    CURRENT_LIAB_BALANCE_YOY         DOUBLE,
    CURRENT_LIAB_OTHER_YOY           DOUBLE,
    DEFER_INCOME_1YEAR_YOY           DOUBLE,
    DEFER_INCOME_YOY                 DOUBLE,
    DEFER_TAX_ASSET_YOY              DOUBLE,
    DEFER_TAX_LIAB_YOY               DOUBLE,
    DERIVE_FINASSET_YOY              DOUBLE,
    DERIVE_FINLIAB_YOY               DOUBLE,
    DEVELOP_EXPENSE_YOY              DOUBLE,
    DIV_HOLDSALE_ASSET_YOY           DOUBLE,
    DIV_HOLDSALE_LIAB_YOY            DOUBLE,
    DIVIDEND_PAYABLE_YOY             DOUBLE,
    DIVIDEND_RECE_YOY                DOUBLE,
    EQUITY_BALANCE_YOY               DOUBLE,
    EQUITY_OTHER_YOY                 DOUBLE,
    EXPORT_REFUND_RECE_YOY           DOUBLE,
    FEE_COMMISSION_PAYABLE_YOY       DOUBLE,
    FIN_FUND_YOY                     DOUBLE,
    FINANCE_RECE_YOY                 DOUBLE,
    FIXED_ASSET_DISPOSAL_YOY         DOUBLE,
    FIXED_ASSET_YOY                  DOUBLE,
    FVTOCI_FINASSET_YOY              DOUBLE,
    FVTOCI_NCFINASSET_YOY            DOUBLE,
    FVTPL_FINASSET_YOY               DOUBLE,
    FVTPL_FINLIAB_YOY                DOUBLE,
    GENERAL_RISK_RESERVE_YOY         DOUBLE,
    GOODWILL_YOY                     DOUBLE,
    HOLD_MATURITY_INVEST_YOY         DOUBLE,
    HOLDSALE_ASSET_YOY               DOUBLE,
    HOLDSALE_LIAB_YOY                DOUBLE,
    INSURANCE_CONTRACT_RESERVE_YOY   DOUBLE,
    INTANGIBLE_ASSET_YOY             DOUBLE,
    INTEREST_PAYABLE_YOY             DOUBLE,
    INTEREST_RECE_YOY                DOUBLE,
    INTERNAL_PAYABLE_YOY             DOUBLE,
    INTERNAL_RECE_YOY                DOUBLE,
    INVENTORY_YOY                    DOUBLE,
    INVEST_REALESTATE_YOY            DOUBLE,
    LEASE_LIAB_YOY                   DOUBLE,
    LEND_FUND_YOY                    DOUBLE,
    LIAB_BALANCE_YOY                 DOUBLE,
    LIAB_EQUITY_BALANCE_YOY          DOUBLE,
    LIAB_EQUITY_OTHER_YOY            DOUBLE,
    LIAB_OTHER_YOY                   DOUBLE,
    LOAN_ADVANCE_YOY                 DOUBLE,
    LOAN_PBC_YOY                     DOUBLE,
    LONG_EQUITY_INVEST_YOY           DOUBLE,
    LONG_LOAN_YOY                    DOUBLE,
    LONG_PAYABLE_YOY                 DOUBLE,
    LONG_PREPAID_EXPENSE_YOY         DOUBLE,
    LONG_RECE_YOY                    DOUBLE,
    LONG_STAFFSALARY_PAYABLE_YOY     DOUBLE,
    MINORITY_EQUITY_YOY              DOUBLE,
    MONETARYFUNDS_YOY                DOUBLE,
    NONCURRENT_ASSET_1YEAR_YOY       DOUBLE,
    NONCURRENT_ASSET_BALANCE_YOY     DOUBLE,
    NONCURRENT_ASSET_OTHER_YOY       DOUBLE,
    NONCURRENT_LIAB_1YEAR_YOY        DOUBLE,
    NONCURRENT_LIAB_BALANCE_YOY      DOUBLE,
    NONCURRENT_LIAB_OTHER_YOY        DOUBLE,
    NOTE_ACCOUNTS_PAYABLE_YOY        DOUBLE,
    NOTE_ACCOUNTS_RECE_YOY           DOUBLE,
    NOTE_PAYABLE_YOY                 DOUBLE,
    NOTE_RECE_YOY                    DOUBLE,
    OIL_GAS_ASSET_YOY                DOUBLE,
    OTHER_COMPRE_INCOME_YOY          DOUBLE,
    OTHER_CREDITOR_INVEST_YOY        DOUBLE,
    OTHER_CURRENT_ASSET_YOY          DOUBLE,
    OTHER_CURRENT_LIAB_YOY           DOUBLE,
    OTHER_EQUITY_INVEST_YOY          DOUBLE,
    OTHER_EQUITY_OTHER_YOY           DOUBLE,
    OTHER_EQUITY_TOOL_YOY            DOUBLE,
    OTHER_NONCURRENT_ASSET_YOY       DOUBLE,
    OTHER_NONCURRENT_FINASSET_YOY    DOUBLE,
    OTHER_NONCURRENT_LIAB_YOY        DOUBLE,
    OTHER_PAYABLE_YOY                DOUBLE,
    OTHER_RECE_YOY                   DOUBLE,
    PARENT_EQUITY_BALANCE_YOY        DOUBLE,
    PARENT_EQUITY_OTHER_YOY          DOUBLE,
    PERPETUAL_BOND_PAYBALE_YOY       DOUBLE,
    PERPETUAL_BOND_YOY               DOUBLE,
    PREDICT_CURRENT_LIAB_YOY         DOUBLE,
    PREDICT_LIAB_YOY                 DOUBLE,
    PREFERRED_SHARES_PAYBALE_YOY     DOUBLE,
    PREFERRED_SHARES_YOY             DOUBLE,
    PREMIUM_RECE_YOY                 DOUBLE,
    PREPAYMENT_YOY                   DOUBLE,
    PRODUCTIVE_BIOLOGY_ASSET_YOY     DOUBLE,
    PROJECT_MATERIAL_YOY             DOUBLE,
    RC_RESERVE_RECE_YOY              DOUBLE,
    REINSURE_PAYABLE_YOY             DOUBLE,
    REINSURE_RECE_YOY                DOUBLE,
    SELL_REPO_FINASSET_YOY           DOUBLE,
    SETTLE_EXCESS_RESERVE_YOY        DOUBLE,
    SHARE_CAPITAL_YOY                DOUBLE,
    SHORT_BOND_PAYABLE_YOY           DOUBLE,
    SHORT_FIN_PAYABLE_YOY            DOUBLE,
    SHORT_LOAN_YOY                   DOUBLE,
    SPECIAL_PAYABLE_YOY              DOUBLE,
    SPECIAL_RESERVE_YOY              DOUBLE,
    STAFF_SALARY_PAYABLE_YOY         DOUBLE,
    SUBSIDY_RECE_YOY                 DOUBLE,
    SURPLUS_RESERVE_YOY              DOUBLE,
    TAX_PAYABLE_YOY                  DOUBLE,
    TOTAL_ASSETS_YOY                 DOUBLE,
    TOTAL_CURRENT_ASSETS_YOY         DOUBLE,
    TOTAL_CURRENT_LIAB_YOY           DOUBLE,
    TOTAL_EQUITY_YOY                 DOUBLE,
    TOTAL_LIAB_EQUITY_YOY            DOUBLE,
    TOTAL_LIABILITIES_YOY            DOUBLE,
    TOTAL_NONCURRENT_ASSETS_YOY      DOUBLE,
    TOTAL_NONCURRENT_LIAB_YOY        DOUBLE,
    TOTAL_OTHER_PAYABLE_YOY          DOUBLE,
    TOTAL_OTHER_RECE_YOY             DOUBLE,
    TOTAL_PARENT_EQUITY_YOY          DOUBLE,
    TRADE_FINASSET_NOTFVTPL_YOY      DOUBLE,
    TRADE_FINASSET_YOY               DOUBLE,
    TRADE_FINLIAB_NOTFVTPL_YOY       DOUBLE,
    TRADE_FINLIAB_YOY                DOUBLE,
    TREASURY_SHARES_YOY              DOUBLE,
    UNASSIGN_RPOFIT_YOY              DOUBLE,
    UNCONFIRM_INVEST_LOSS_YOY        DOUBLE,
    USERIGHT_ASSET_YOY               DOUBLE,
    OPINION_TYPE                     VARCHAR(100),
    OSOPINION_TYPE                   DOUBLE,
    LISTING_STATE                    VARCHAR(100)
)
"""


async def run(
    years: list[int] | None = None,
    periods: str = "Q1,Q2,Q3,FY",
    page_size: int = 100,
    incremental: bool = False,
) -> Path:
    """Fetch balance sheet data and write to CSV.

    With ``incremental=True`` a single ``UPDATE_DATE>='anchor'`` pull replaces
    per-period REPORT_DATE enumeration, so historical revisions are captured
    and the full table is not re-fetched on every sync (issue #299). When no
    anchor exists the fixed initial date ``2020-01-01`` is used (one full
    history pull by UPDATE_DATE), never a REPORT_DATE enumeration fallback.

    Returns the path to the generated CSV file.
    """
    output_path = csv_dir() / f"{REPORT_NAME}.csv"

    if incremental:
        state_path = csv_dir() / f"{REPORT_NAME}.state.json"
        anchor = update_date_anchor(REPORT_NAME, state_path, dolt_table=DOLT_TABLE)
        if not anchor:
            anchor = INITIAL_UPDATE_ANCHOR
            print(
                f"No prior anchor found; using UPDATE_DATE>='{anchor}' for one full-history pull",
                file=sys.stderr,
            )
        print(f"Report: {REPORT_NAME}", file=sys.stderr)
        print(f"Update filter: UPDATE_DATE>='{anchor}' (ignores --years/--periods)", file=sys.stderr)
        print(f"Output: {output_path.resolve()}", file=sys.stderr)
        print(file=sys.stderr)

        throttle = Throttle()
        pool = make_proxy_pool()
        total_records = 0
        max_report_date = ""
        max_update_date = ""

        async with AsyncSession(impersonate="chrome142") as session:
            print(
                f"[1/1] UPDATE_DATE>='{anchor}' ...", file=sys.stderr, end=" ", flush=True
            )
            try:
                records = await fetch_by_update_date(
                    session, throttle, REPORT_NAME, anchor, page_size, pool=pool
                )
            except Exception as e:
                print(f"FAILED: {e}", file=sys.stderr)
                records = []

            if records:
                write_csv(records, output_path, append=False)
                total_records += len(records)
                for rec in records:
                    rpt = rec.get("REPORT_DATE") or ""
                    if rpt:
                        max_report_date = max(max_report_date, rpt)
                    upd = normalize_update_date(rec.get("UPDATE_DATE"))
                    if upd:
                        max_update_date = max(max_update_date, upd)
                dedupe_csv(output_path, date_col="REPORT_DATE")
                print(f"{len(records)} records", file=sys.stderr)
            else:
                print("empty", file=sys.stderr)

        if total_records > 0:
            state = {
                "last_report_date": max_report_date,
                "total_rows": total_records,
                "last_run": datetime.now().isoformat(),
            }
            if not max_update_date:
                # All fetched rows had empty/missing UPDATE_DATE: preserve the
                # previous anchor (never advance, never regress).
                try:
                    prev = (
                        json.loads(state_path.read_text()).get("last_update_date", "")
                        if state_path.exists()
                        else ""
                    )
                except (json.JSONDecodeError, OSError):
                    prev = ""
                max_update_date = prev
            today = date.today().isoformat()
            if max_update_date > today:
                max_update_date = today
            state["last_update_date"] = max_update_date
            state_path.write_text(json.dumps(state, indent=2))

        print(f"\nDone: {total_records} records → {output_path.resolve()}", file=sys.stderr)
        return output_path

    if years is None:
        years = list(range(START_YEAR, datetime.now().year + 1))

    period_list = [p.strip() for p in periods.split(",")]
    all_dates = build_dates(years, period_list)

    since = last_report_date(DOLT_TABLE)
    if since:
        print(f"Last report date in Dolt: {since}, fetching only newer periods", file=sys.stderr)
        all_dates = [d for d in all_dates if d >= since]
        if not all_dates:
            print("No new report periods to fetch.", file=sys.stderr)
            return output_path

    print(f"Report: {REPORT_NAME}", file=sys.stderr)
    print(
        f"Periods: {len(all_dates)} ({periods}, "
        f"{all_dates[0] if all_dates else 'none'}..{all_dates[-1] if all_dates else 'none'})",
        file=sys.stderr,
    )
    print(f"Output: {output_path.resolve()}", file=sys.stderr)
    print(file=sys.stderr)

    throttle = Throttle()
    pool = make_proxy_pool()
    total_records = 0
    first_write = True

    async with AsyncSession(impersonate="chrome142") as session:
        for i, report_date in enumerate(all_dates):
            print(
                f"[{i + 1}/{len(all_dates)}] {report_date} ...",
                file=sys.stderr, end=" ", flush=True,
            )
            try:
                records = await fetch_paginated(
                    session, throttle, REPORT_NAME, FILTER_COLUMN, report_date, page_size,
                    pool=pool,
                )
            except Exception as e:
                print(f"FAILED: {e}", file=sys.stderr)
                continue

            if records:
                write_csv(records, output_path, append=not first_write)
                first_write = False
                print(f"{len(records)} records", file=sys.stderr)
            else:
                print("empty", file=sys.stderr)
            total_records += len(records)

    print(f"\nDone: {total_records} records → {output_path.resolve()}", file=sys.stderr)
    return output_path


def import_to_dolt(csv_path: Path | None = None) -> int:
    """Import the fetched CSV into Dolt fin_balance_sheet (merge/upsert semantics).

    Incremental CSVs are UPSERTed into the existing table keyed by the PK
    (symbol, report_date): new rows append to history while revised rows
    (same PK, moved UPDATE_DATE) OVERWRITE the old row across every non-PK
    value column. Writing constraint (Dolt 2.2.3): SELECT-side unique
    aliases + ODKU unqualified alias refs — qualified source refs fail on
    TRIM-wrapped text columns and VALUES() is unsupported (issue #299).
    """
    csv_path = csv_path or csv_dir() / f"{REPORT_NAME}.csv"
    print("[import balance_sheet]", file=sys.stderr)

    return import_replace_table(
        csv_path=csv_path,
        tmp_name="_tmp_bs",
        ddl=DDL,
        insert_sql=f"""
            INSERT INTO {DOLT_TABLE} (symbol, report_date, {COLS})
            SELECT
                CONCAT(UPPER(SUBSTRING_INDEX(SECUCODE, '.', -1)), SECURITY_CODE) AS _sym,
                CAST(REPORT_DATE AS DATE) AS _rpt, {_upsert_select_cols()}
            FROM _tmp_bs
            WHERE CONCAT(UPPER(SUBSTRING_INDEX(SECUCODE, '.', -1)), SECURITY_CODE)
                  IN (SELECT symbol FROM stock_basic)
            ON DUPLICATE KEY UPDATE
                {_upsert_updates()}
        """,
        create_sql=_TMP_BS_DDL,
        dolt_table=DOLT_TABLE,
        source_label=f"EastMoney datacenter {REPORT_NAME}",
        last_report_expr="MAX(report_date)",
        merge=True,
    )


# Standalone entry point (also callable via main.py)
if __name__ == "__main__":
    import argparse

    async def _main() -> None:
        p = argparse.ArgumentParser(description="Fetch A-share balance sheet")
        p.add_argument("--years", default="")
        p.add_argument("--periods", default="Q1,Q2,Q3,FY")
        p.add_argument("--incremental", action="store_true")
        args = p.parse_args()
        await run(
            years=[int(y) for y in args.years.split(",") if y] or None,
            periods=args.periods,
            incremental=args.incremental,
        )

    asyncio.run(_main())
